name: Deploying app to github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying app to github pages
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Get yarn cache directory
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Set dependencies cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-${{ matrix.node_version }}-

    - name: Versions
      run: yarn versions

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build
      run: npx vue-tsc --noEmit && npx vite build --base=${{ github.event.repository.name }}

    - name: Copy file
      run: cp -R "dist/index.html" "dist/404.html"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
      env:
        CI: true