name: Deploying app to github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying app to github pages
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Get yarn cache directory
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Set dependencies cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node_version }}-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-${{ matrix.node_version }}-

    - name: Versions
      run: yarn versions

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # - name: Set ENV
    - run: BUILD_PATH=".gh-pages"
    - run: BASE_URL=${{ github.event.repository.name }}
    - run: BASE_URL_ODIR="${BUILD_PATH}/${BASE_URL}"

    - name: Build
      run: yarn build

    - name: Copy file
      run: cp -R "${BUILD_PATH}/index.html" "${BUILD_PATH}/400.html"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${BUILD_PATH}
      env:
        CI: true